#!/usr/bin/env python3
"""lichess-standard-rated-v1 selection tool (S6 third source family).

Streams official Lichess monthly standard-rated .pgn.zst files (CC0) with
python-zstandard - never extracts the full archive to disk. The COMPRESSED
stream is SHA-256-verified in flight against the official per-month checksum
from the upstream `sha256sums.txt`; a missing or mismatching checksum fails
closed. Deterministic selection: hash(GameURL + selection_seed) first byte
< threshold, capped per month and per long-game stratum.

filters (matches passes() exactly):
  Result in {1-0, 0-1, 1/2-1/2}
  WhiteElo >= 1800 and BlackElo >= 1800
  WhiteTitle != BOT and BlackTitle != BOT
  TimeControl base >= 180 sec   (the speed gate is TimeControl, NOT Event)
  mainline >= 40 plies

The database covers standard chess across all time controls (Event values
like "Rated Rapid tournament ..."), so the Event tag is deliberately not a
filter. long-game stratum: ~1/3 of selected games must have >= 80 plies
(deterministic).

Identity / exclusion (S6-N3D): every candidate gets a deterministic game
fingerprint - sha256 over canonical JSON of EXACTLY three fields:
`initial_fen` (the standard initial position when the PGN carries no FEN
header), `result`, and the mainline UCI move list. Headers, players, Elo,
timestamps and the Site URL are deliberately NOT part of it, so the same game
fingerprints identically regardless of how it was exported. `--exclude-pgn`
loads fingerprints from already-used PGNs and skips them; a candidate whose
fingerprint was already selected in this run is rejected too. The published
manifest records both key-set SHAs and asserts an empty intersection.

Selection stays O(number selected) in memory: fingerprint sets and counters
only, never a list of parsed games, and a fresh StringExporter per written
game (StringExporter accumulates across calls). The archive is read by
exactly one sequential reader.

Outputs (staged, then atomically published; nothing is published if any month
selects fewer than --games-per-month games):
  out/<source-id>.pgn                selected games (raw, with headers)
  out/source-manifest.json           provenance (CC0, upstream URLs, official
                                     SHA256s, script SHA, selection seed,
                                     counts, fingerprint key SHAs, output
                                     SHA256)

Usage:
  python tools/s6/lichess_select.py \
      --months 2026-07 \
      --games-per-month 2000 \
      --seed 20260812 \
      --out data/s6/sources/lichess-standard-rated-v1
  (add --local <file.zst> to read a pre-downloaded, SHA-verified archive)

  S6-N3D confirmation source (1000 unseen games from the same archive):
  python tools/s6/lichess_select.py \
      --months 2026-07 --games-per-month 1000 --seed 20260821 \
      --source-id lichess-standard-rated-confirm-v1 \
      --source-family lichess-standard-rated-v1 \
      --exclude-pgn data/s6/sources/lichess-standard-rated-v1/\
lichess-standard-rated-v1.pgn \
      --local <archive.zst> \
      --out data/s6/sources/lichess-standard-rated-confirm-v1

The frozen lichess-standard-rated-v1 PGN (pgn_sha256 d81ffe3c...) is NOT
regenerated by this change; duplicate-fingerprint rejection is a no-op for
distinct >=40-ply games.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import shutil
import sys
import time
import urllib.request
from pathlib import Path

import chess
import chess.pgn
import zstandard

BASE = "https://database.lichess.org/standard/"
CHECKSUMS_URL = BASE + "sha256sums.txt"
TIME_CONTROL_BASE_MIN = 180
LONG_GAME_FRACTION = 1.0 / 3.0
ACCEPT_BYTE = 0x05  # ~2% of passing games accepted
FINGERPRINT_FIELDS = ("initial_fen", "result", "moves")


def time_control_base(tc: str) -> int:
    base = tc.split("+")[0]
    try:
        return int(base)
    except ValueError:
        return 0


def game_fingerprint(game: chess.pgn.Game) -> str:
    """Deterministic identity of a game: sha256(canonical JSON).

    EXACTLY three fields, and nothing else: the initial position (standard
    start when the PGN has no FEN header), the result, and the mainline moves
    in UCI. Two exports of the same game - different headers, different
    whitespace, different key order - fingerprint identically.
    """
    headers = game.headers
    payload = {
        "initial_fen": headers.get("FEN") or chess.STARTING_FEN,
        "result": headers.get("Result", ""),
        "moves": [move.uci() for move in game.mainline_moves()],
    }
    if set(payload) != set(FINGERPRINT_FIELDS):
        raise SystemExit("FAIL CLOSED: fingerprint field set drifted")
    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=False,
                           separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def fingerprint_set_sha256(fingerprints: set[str]) -> str:
    """Order-independent SHA of a fingerprint set (sorted, newline joined)."""
    return hashlib.sha256(
        "\n".join(sorted(fingerprints)).encode("utf-8")).hexdigest()


def ordered_pgn_fingerprints(path: Path) -> list[str]:
    """Fingerprints of every game in a PGN, in file (selection) order.

    Streamed: one Game object alive at a time, only the fingerprint strings
    are retained.
    """
    fingerprints: list[str] = []
    with open(path, encoding="utf-8", errors="replace") as fh:
        while True:
            game = chess.pgn.read_game(fh)
            if game is None:
                break
            fingerprints.append(game_fingerprint(game))
    return fingerprints


def is_ordered_subsequence(inner: list[str], outer: list[str]) -> bool:
    """True when `inner` appears inside `outer` in the same relative order.

    This is the exact relationship between a games-per-month N selection and
    a larger N' > N selection over the SAME archive, seed and exclude set.
    Both runs see an identical candidate stream; the smaller run's long/short
    stratum caps (int(N/3) and N - int(N/3)) are strictly tighter, and the two
    runs' per-stratum counters stay equal until the smaller run first rejects
    a candidate, so anything the smaller run accepts the larger run accepts
    too. The smaller selection is therefore a subsequence of the larger one -
    but NOT a contiguous prefix, because once the smaller run saturates a
    stratum it drops candidates the larger run still keeps.
    """
    iterator = iter(outer)
    return all(key in iterator for key in inner)


def load_exclude_fingerprints(paths: list[Path]) -> tuple[set[str], list[dict]]:
    """Fingerprints of every game in the already-used PGNs.

    Streams game by game; only fingerprints are retained, never Game objects.
    """
    excluded: set[str] = set()
    sources: list[dict] = []
    for path in paths:
        if not path.is_file():
            raise SystemExit(f"FAIL CLOSED: --exclude-pgn missing {path}")
        games = 0
        with open(path, encoding="utf-8", errors="replace") as fh:
            while True:
                game = chess.pgn.read_game(fh)
                if game is None:
                    break
                games += 1
                excluded.add(game_fingerprint(game))
        if games == 0:
            raise SystemExit(f"FAIL CLOSED: --exclude-pgn {path} has no games")
        sources.append({
            "path": str(path),
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "games": games,
        })
        print(f"exclude source {path}: {games} games", flush=True)
    return excluded, sources


def write_game(game: chess.pgn.Game, fh) -> None:
    """Write one game with a FRESH exporter (StringExporter accumulates).

    The settings match what `str(game)` used before this was made explicit -
    `columns=None`, comments and variations kept - so the published PGN stays
    byte-identical in format to the frozen lichess-standard-rated-v1 output,
    including the `[%clk ...]` move comments the archive carries.
    """
    exporter = chess.pgn.StringExporter(columns=None)
    fh.write(game.accept(exporter))
    fh.write("\n\n")


def passes(game: chess.pgn.Game) -> bool:
    h = game.headers
    if h.get("Result") not in ("1-0", "0-1", "1/2-1/2"):
        return False
    if h.get("WhiteTitle") == "BOT" or h.get("BlackTitle") == "BOT":
        return False
    try:
        if int(h.get("WhiteElo", "0")) < 1800 or int(h.get("BlackElo", "0")) < 1800:
            return False
    except ValueError:
        return False
    if time_control_base(h.get("TimeControl", "0")) < TIME_CONTROL_BASE_MIN:
        return False
    if len(list(game.mainline_moves())) < 40:
        return False
    return True


def select_key(game: chess.pgn.Game) -> str:
    h = game.headers
    url = h.get("Site", "")
    if url:
        return url
    return "|".join([h.get("White", ""), h.get("Black", ""),
                     h.get("Date", ""), h.get("Round", ""),
                     h.get("Result", "")])


class HashingReader:
    """File-like wrapper that feeds every read into a live SHA-256.

    `read(0)` returns b"" without consuming (probe semantics); `read()` and
    `read(-1)` read one bounded chunk so a slow/high-latency source can never
    stall the caller, and every byte served is hashed exactly once.
    """

    def __init__(self, resp, hasher):
        self._resp = resp
        self._hasher = hasher

    def read(self, size: int = -1) -> bytes:
        if size == 0:
            return b""
        if size is None or size < 0:
            size = 1 << 20
        data = self._resp.read(size)
        if data:
            self._hasher.update(data)
        return data

    def hexdigest(self) -> str:
        return self._hasher.hexdigest()


def fetch_official_sha256(month: str) -> str:
    """Official checksum for one monthly archive from sha256sums.txt."""
    try:
        with urllib.request.urlopen(CHECKSUMS_URL, timeout=60) as resp:
            text = resp.read().decode("utf-8", errors="replace")
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(
            f"FAIL CLOSED: cannot fetch official sha256sums.txt: {exc}")
    filename = f"lichess_db_standard_rated_{month}.pgn.zst"
    for line in text.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1].endswith(filename):
            return parts[0].strip().lower()
    raise SystemExit(
        f"FAIL CLOSED: no official SHA256 for {filename} in sha256sums.txt")


def open_month_stream(month: str, local: Path | None):
    """Return (reader, hashing_reader, raw, official, display).

    `hashing_reader` is THE object the caller must drain to EOF after
    selection: it is the single point through which every compressed byte is
    hashed exactly once (by the decompressor and by the final drain). The
    caller must close text/reader/raw explicitly.
    """
    url = f"{BASE}lichess_db_standard_rated_{month}.pgn.zst"
    official = fetch_official_sha256(month)
    if local is not None:
        raw = open(local, "rb")
        display = str(local)
    else:
        try:
            raw = urllib.request.urlopen(url, timeout=120)
        except Exception as exc:  # noqa: BLE001
            raise SystemExit(f"FAIL CLOSED: cannot open {url}: {exc}") from exc
        display = url
    hasher = hashlib.sha256()
    hashing_reader = HashingReader(raw, hasher)
    dctx = zstandard.ZstdDecompressor()
    reader = dctx.stream_reader(hashing_reader)
    return reader, hashing_reader, raw, official, display


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--months", default="2026-05,2026-06,2026-07")
    parser.add_argument("--games-per-month", type=int, default=12000)
    parser.add_argument("--seed", type=int, default=20260812)
    parser.add_argument("--out", required=True)
    parser.add_argument("--local", type=Path, default=None,
                        help="pre-downloaded monthly archive (single month); "
                             "SHA-verified against the official checksum")
    parser.add_argument("--official-sha256", default="",
                        help="legacy 'month=sha,...' override (unused when "
                             "sha256sums.txt is reachable)")
    parser.add_argument("--source-id", default="lichess-standard-rated-v1",
                        help="source identity; also the output PGN basename")
    parser.add_argument("--source-family",
                        default="lichess-standard-rated-v1",
                        help="source family (confirmation shares the v1 "
                             "family while carrying its own source_id)")
    parser.add_argument("--exclude-pgn", type=Path, action="append",
                        default=None,
                        help="PGN whose games must NOT be selected; matched "
                             "by deterministic game fingerprint (repeatable)")
    args = parser.parse_args(sys.argv[1:])

    out_dir = Path(args.out)
    if out_dir.exists():
        print(f"FAIL CLOSED: {out_dir} already exists; refusing to overwrite")
        return 3
    months = [m.strip() for m in args.months.split(",")]
    if args.local is not None and len(months) != 1:
        raise SystemExit("FAIL CLOSED: --local requires exactly one --months")
    long_target = int(args.games_per_month * LONG_GAME_FRACTION)
    total = 0
    t0 = time.time()
    script_sha = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()

    excluded_fingerprints, exclude_sources = load_exclude_fingerprints(
        list(args.exclude_pgn or []))
    selected_fingerprints: set[str] = set()
    excluded_hits = 0
    duplicate_hits = 0

    staging = Path(str(out_dir) + ".staging")
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True, exist_ok=True)
    pgn_path = staging / f"{args.source_id}.pgn"
    official_sha256: dict[str, str] = {}

    with open(pgn_path, "w", encoding="utf-8") as fh:
        for month in months:
            reader, hashing_reader, raw, official, display = \
                open_month_stream(month, args.local)
            official_sha256[month] = official
            print(f"streaming {display} (official sha {official[:16]}...)",
                  flush=True)
            month_selected = 0
            month_long = 0
            seen = 0
            text = io.TextIOWrapper(reader, encoding="utf-8", errors="replace")
            try:
                while month_selected < args.games_per_month:
                    game = chess.pgn.read_game(text)
                    if game is None:
                        break
                    seen += 1
                    if not passes(game):
                        continue
                    key = select_key(game)
                    h = hashlib.sha256(
                        f"{key}:{args.seed}".encode("utf-8")).digest()
                    if h[0] >= ACCEPT_BYTE:
                        continue
                    # Identity gates BEFORE the stratum caps, so an excluded
                    # or duplicate game never consumes a stratum slot.
                    fingerprint = game_fingerprint(game)
                    if fingerprint in excluded_fingerprints:
                        excluded_hits += 1
                        continue
                    if fingerprint in selected_fingerprints:
                        duplicate_hits += 1
                        continue
                    is_long = len(list(game.mainline_moves())) >= 80
                    if is_long:
                        if month_long >= long_target:
                            continue
                        month_long += 1
                    elif month_selected - month_long >= \
                            args.games_per_month - long_target:
                        continue
                    month_selected += 1
                    selected_fingerprints.add(fingerprint)
                    write_game(game, fh)
                # Consume the ENTIRE compressed stream THROUGH the hashing
                # reader so every byte is hashed exactly once, then fail
                # closed on any mismatch.
                while hashing_reader.read(1 << 20):
                    pass
                actual = hashing_reader.hexdigest()
                if actual != official:
                    print(
                        f"FAIL CLOSED: stream SHA mismatch for {month}: "
                        f"{actual[:12]} != {official[:12]}", flush=True)
                    return 5
                if month_selected < args.games_per_month:
                    print(
                        f"FAIL CLOSED: {month} selected only {month_selected} "
                        f"games (< {args.games_per_month}); staging NOT "
                        f"published", flush=True)
                    return 4
            finally:
                text.close()
                reader.close()
                raw.close()
            total += month_selected
            elapsed = time.time() - t0
            print(f"{month}: {month_selected} selected ({month_long} long) "
                  f"of {seen} passing-eligible seen, {elapsed:.0f}s",
                  flush=True)

    intersection = len(selected_fingerprints & excluded_fingerprints)
    if intersection != 0:
        print(f"FAIL CLOSED: {intersection} selected games overlap the "
              f"exclude fingerprint set", flush=True)
        return 6
    if len(selected_fingerprints) != total:
        print(f"FAIL CLOSED: {len(selected_fingerprints)} unique fingerprints "
              f"!= {total} selected games", flush=True)
        return 6

    manifest = {
        "source_family": args.source_family,
        "source_id": args.source_id,
        "license": "CC0",
        "upstream": [f"{BASE}lichess_db_standard_rated_{m}.pgn.zst"
                     for m in months],
        "official_sha256": official_sha256,
        "script_sha256": script_sha,
        "selection_seed": args.seed,
        "filters": {
            "database": "standard rated (all standard-chess time controls)",
            "event_filter": "none (TimeControl is the speed gate)",
            "elo_min": 1800,
            "no_bot_titles": True,
            "time_control_base_min_sec": TIME_CONTROL_BASE_MIN,
            "mainline_plies_min": 40,
            "long_stratum_plies_min": 80,
            "long_fraction": LONG_GAME_FRACTION,
        },
        "games_selected": total,
        "selection": "hash(GameURL, seed) first byte < 0x05, capped per "
                     "month and per long stratum",
        "fingerprint": {
            "definition": "sha256(canonical JSON with sorted keys and no "
                          "whitespace)",
            "fields": list(FINGERPRINT_FIELDS),
            "initial_fen_default": chess.STARTING_FEN,
            "moves_encoding": "mainline UCI",
        },
        "exclude_sources": exclude_sources,
        "exclude_fingerprint_count": len(excluded_fingerprints),
        "exclude_fingerprints_sha256": fingerprint_set_sha256(
            excluded_fingerprints),
        "selected_fingerprint_count": len(selected_fingerprints),
        "selected_fingerprints_sha256": fingerprint_set_sha256(
            selected_fingerprints),
        "fingerprint_intersection": intersection,
        "excluded_candidates_skipped": excluded_hits,
        "duplicate_candidates_rejected": duplicate_hits,
        "pgn_sha256": hashlib.sha256(pgn_path.read_bytes()).hexdigest(),
        "finished_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    (staging / "source-manifest.json").write_text(
        json.dumps(manifest, indent=2))
    shutil.move(str(staging), str(out_dir))
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
