# stage_s14_gui.ps1 - stage the frozen S14 NNUE model next to the built Windows
# engine and write a ready-to-paste En Croissant setup note.
#
# Usage (from the repo root, or anywhere):
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1 -Build
#
# -Build runs `cargo build --release` first. Close En Croissant before -Build:
# Windows locks eureka.exe while a GUI has it loaded and cargo will fail to
# replace it (os error 5, access denied).
param(
    [switch]$Build
)

$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
$modelRel = "data\s14\run\seed-20260908\nnue-s14-datasupply-v5.bin"
$expectedSha = "329b717066082798d2f42d9e4f137385a1482a8cda03ae7849ddc654e097e4b0"
$targetDir = Join-Path $repo "target\release"
$engineExe = Join-Path $targetDir "eureka.exe"
$sourceModel = Join-Path $repo $modelRel
$stagedModel = Join-Path $targetDir "nnue-s14-datasupply-v5.bin"
$notePath = Join-Path $targetDir "EN-CROISSANT-S14.txt"

if ($Build) {
    Push-Location $repo
    try {
        Write-Host "[stage] cargo build --release ..."
        & cargo build --release
        if ($LASTEXITCODE -ne 0) {
            throw "cargo build failed with exit code $LASTEXITCODE (is En Croissant holding eureka.exe?)"
        }
    } finally {
        Pop-Location
    }
}

if (-not (Test-Path -LiteralPath $sourceModel)) {
    throw "frozen S14 model not found: $sourceModel"
}
if (-not (Test-Path -LiteralPath $engineExe)) {
    throw "engine not built: $engineExe (run cargo build --release, or re-run with -Build)"
}

$sha = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceModel).Hash.ToLowerInvariant()
if ($sha -ne $expectedSha) {
    throw "model SHA-256 mismatch (fail closed).`n  expected: $expectedSha`n  actual:   $sha"
}

Copy-Item -LiteralPath $sourceModel -Destination $stagedModel -Force

$stagedPath = (Resolve-Path -LiteralPath $stagedModel).Path
$enginePath = (Resolve-Path -LiteralPath $engineExe).Path

$legacyModel = Join-Path $targetDir "nnue-v2-q01.bin"
if (Test-Path -LiteralPath $legacyModel) {
    Write-Host "[stage] note: legacy nnue-v2-q01.bin found in target\release; leave EvalFile/NnueMode at their defaults (do not use the option route with the S14 model - see the staged note)."
}

$note = @"
Eureka local setup - S14 NNUE (staged for the UCI-option route)
(generated by tools\stage_s14_gui.ps1)

Engine path:
  $enginePath

En Croissant settings (En Croissant configures engines through UCI options;
there is no launch-arguments field):
  Evaluation = nnue             (default is classical = HCE)
  EvalFile  = "$stagedPath"

Notes:
  - The evaluator is built from the artifact's own metadata (material-residual
    composition, R12 relation handling, incremental delivery) - no model-format
    option is needed. The old NnueMode option is ignored/obsolete.
  - Requires an engine binary built AFTER the S14 evaluator-unification fix;
    older binaries mis-evaluate residual artifacts in the option route -
    rebuild first (close En Croissant).
  - Switching the evaluator clears the transposition table.
  - A missing/unloadable EvalFile fails closed ("refusing to search") - it
    never silently falls back.

Equivalent startup-profile form (CLI / Arena preset):
  --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin
  (a relative --nnue-model resolves against this executable's directory)

This is the strongest Eureka configuration: S14 NNUE + CurrentFinal search,
the same combination that passed the formal promotion SPRT (ACCEPT_H1).

Model:
  $stagedPath
  sha256 $expectedSha

After pulling new engine code (close En Croissant first):
  cargo build --release
  powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1
"@

Set-Content -LiteralPath $notePath -Value $note -Encoding ASCII

Write-Host "[stage] model staged -> $stagedPath"
Write-Host "[stage] note written -> $notePath"
Write-Host "[stage] En Croissant settings: Evaluation = nnue ; EvalFile = `"$stagedPath`""
Write-Host "[stage] (profile route: --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin)"
