# stage_s14_gui.ps1 - stage the frozen S14 NNUE model next to the built Windows
# engine and write a ready-to-paste En Croissant setup note.
#
# Usage (from the repo root, or anywhere):
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1 -Build
#
# -Build runs `cargo build --release` first. Close En Croissant before -Build:
# Windows locks eureka.exe while a GUI has it loaded and cargo will fail to
# replace it (os error 5, access denied).
param(
    [switch]$Build
)

$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
$modelRel = "data\s14\run\seed-20260908\nnue-s14-datasupply-v5.bin"
$expectedSha = "329b717066082798d2f42d9e4f137385a1482a8cda03ae7849ddc654e097e4b0"
$targetDir = Join-Path $repo "target\release"
$engineExe = Join-Path $targetDir "eureka.exe"
$sourceModel = Join-Path $repo $modelRel
$stagedModel = Join-Path $targetDir "nnue-s14-datasupply-v5.bin"
$notePath = Join-Path $targetDir "EN-CROISSANT-S14.txt"

if ($Build) {
    Push-Location $repo
    try {
        Write-Host "[stage] cargo build --release ..."
        & cargo build --release
        if ($LASTEXITCODE -ne 0) {
            throw "cargo build failed with exit code $LASTEXITCODE (is En Croissant holding eureka.exe?)"
        }
    } finally {
        Pop-Location
    }
}

if (-not (Test-Path -LiteralPath $sourceModel)) {
    throw "frozen S14 model not found: $sourceModel"
}
if (-not (Test-Path -LiteralPath $engineExe)) {
    throw "engine not built: $engineExe (run cargo build --release, or re-run with -Build)"
}

$sha = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceModel).Hash.ToLowerInvariant()
if ($sha -ne $expectedSha) {
    throw "model SHA-256 mismatch (fail closed).`n  expected: $expectedSha`n  actual:   $sha"
}

Copy-Item -LiteralPath $sourceModel -Destination $stagedModel -Force

$stagedPath = (Resolve-Path -LiteralPath $stagedModel).Path
$enginePath = (Resolve-Path -LiteralPath $engineExe).Path

$legacyModel = Join-Path $targetDir "nnue-v2-q01.bin"
if (Test-Path -LiteralPath $legacyModel) {
    Write-Host "[stage] note: legacy nnue-v2-q01.bin found in target\release - it is reported as the EvalFile handshake default; make sure the EvalFile setting points at the S14 model, not this legacy file."
}

$note = @"
Eureka local setup - S14 NNUE for En Croissant
(generated by tools\stage_s14_gui.ps1)

Engine path:
  $enginePath

En Croissant settings (En Croissant configures engines through UCI options;
there is no launch-arguments field):
  EvalFile = "$stagedPath"
  NnueMode = nnue-v2q          (default is off = HCE)

Notes:
  - NnueMode = nnue-v2q switches the evaluator to the S14 network loaded
    from EvalFile; the search policy is unchanged (S14 NNUE + CurrentFinal
    search). A missing/unloadable EvalFile fails closed ("refusing to
    search") - it never silently falls back.
  - target\release may still contain the legacy nnue-v2-q01.bin (old S10
    model); make sure EvalFile points at nnue-s14-datasupply-v5.bin above,
    not at the legacy file.

Equivalent launch-argument form (CLI / GUIs that accept arguments):
  --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin
  (a relative --nnue-model resolves against this executable's directory)

This is the strongest Eureka configuration: S14 NNUE + CurrentFinal search,
the same combination that passed the formal promotion SPRT (ACCEPT_H1).

Model:
  $stagedPath
  sha256 $expectedSha

After pulling new engine code (close En Croissant first):
  cargo build --release
  powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1
"@

Set-Content -LiteralPath $notePath -Value $note -Encoding ASCII

Write-Host "[stage] model staged -> $stagedPath"
Write-Host "[stage] note written -> $notePath"
Write-Host "[stage] En Croissant settings: EvalFile = `"$stagedPath`" ; NnueMode = nnue-v2q"
Write-Host "[stage] (CLI equivalent: --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin)"
