# stage_s14_gui.ps1 - stage the frozen S14 NNUE model next to the built Windows
# engine and write a ready-to-paste En Croissant setup note.
#
# Usage (from the repo root, or anywhere):
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1
#   powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1 -Build
#
# -Build runs `cargo build --release` first. Close En Croissant before -Build:
# Windows locks eureka.exe while a GUI has it loaded and cargo will fail to
# replace it (os error 5, access denied).
param(
    [switch]$Build
)

$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
$modelRel = "data\s14\run\seed-20260908\nnue-s14-datasupply-v5.bin"
$expectedSha = "329b717066082798d2f42d9e4f137385a1482a8cda03ae7849ddc654e097e4b0"
$targetDir = Join-Path $repo "target\release"
$engineExe = Join-Path $targetDir "eureka.exe"
$sourceModel = Join-Path $repo $modelRel
$stagedModel = Join-Path $targetDir "nnue-s14-datasupply-v5.bin"
$notePath = Join-Path $targetDir "EN-CROISSANT-S14.txt"

if ($Build) {
    Push-Location $repo
    try {
        Write-Host "[stage] cargo build --release ..."
        & cargo build --release
        if ($LASTEXITCODE -ne 0) {
            throw "cargo build failed with exit code $LASTEXITCODE (is En Croissant holding eureka.exe?)"
        }
    } finally {
        Pop-Location
    }
}

if (-not (Test-Path -LiteralPath $sourceModel)) {
    throw "frozen S14 model not found: $sourceModel"
}
if (-not (Test-Path -LiteralPath $engineExe)) {
    throw "engine not built: $engineExe (run cargo build --release, or re-run with -Build)"
}

if (Get-Command Get-FileHash -ErrorAction SilentlyContinue) {
    $sha = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceModel).Hash.ToLowerInvariant()
} else {
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    $stream = [System.IO.File]::OpenRead($sourceModel)
    try {
        $hashBytes = $hasher.ComputeHash($stream)
        $sha = [System.BitConverter]::ToString($hashBytes).Replace('-', '').ToLowerInvariant()
    } finally {
        $stream.Close()
    }
}
if ($sha -ne $expectedSha) {
    throw "model SHA-256 mismatch (fail closed).`n  expected: $expectedSha`n  actual:   $sha"
}

Copy-Item -LiteralPath $sourceModel -Destination $stagedModel -Force

$stagedPath = (Resolve-Path -LiteralPath $stagedModel).Path
$enginePath = (Resolve-Path -LiteralPath $engineExe).Path

$note = @"
Eureka local setup - S14 NNUE
(generated by tools\stage_s14_gui.ps1)

Engine path:
  $enginePath

Recommended CLI launch:
  eureka.exe --evaluation nnue --nnue-model nnue-s14-datasupply-v5.bin
  (a relative --nnue-model resolves against eureka.exe's directory)

En Croissant settings (UCI options):
  Evaluation = nnue             (default is classical = HCE)
  EvalFile   = "$stagedPath"
  Hash       = 16

Notes:
  - The evaluator is built from the artifact's own metadata (material-residual
    composition, R12 relation handling, incremental delivery) - no format
    knob is needed.
  - Switching the evaluator clears the transposition table.
  - A missing/unloadable EvalFile fails closed ("refusing to search") - it
    never silently falls back to HCE.

Legacy compatibility alias (CLI / Arena preset):
  eureka.exe --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin
  (converts to CurrentFinal search + Evaluation=nnue; do not pass --evaluation classical)

Model:
  $stagedPath
  sha256 $expectedSha

After pulling new engine code (close En Croissant first):
  powershell -ExecutionPolicy Bypass -File tools\stage_s14_gui.ps1 -Build
"@

Set-Content -LiteralPath $notePath -Value $note -Encoding ASCII

Write-Host "[stage] model staged -> $stagedPath"
Write-Host "[stage] note written -> $notePath"
Write-Host "[stage] CLI: eureka.exe --evaluation nnue --nnue-model nnue-s14-datasupply-v5.bin"
Write-Host "[stage] GUI (En Croissant): Evaluation = nnue ; EvalFile = `"$stagedPath`""
Write-Host "[stage] Legacy alias: --profile current-final-s12 --nnue-model nnue-s14-datasupply-v5.bin"
